# Generated by Django 3.1.5 on 2021-03-19 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hdd',
            name='manufacturer',
            field=models.CharField(choices=[('Seagate', 'Seagate')], max_length=50),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='manufacturer',
            field=models.CharField(choices=[('ASUSTek COMPUTER INC', 'Asus')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ram',
            name='manufacturer',
            field=models.CharField(choices=[('KINGSTON', 'Kingston'), ('VGEN', 'Vgen')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ram',
            name='size',
            field=models.IntegerField(choices=[(4, '4 GB'), (8, '8 GB')], default=8),
        ),
        migrations.AlterField(
            model_name='ssd',
            name='manufacturer',
            field=models.CharField(choices=[('SanDisk', 'SanDisk')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ssd',
            name='size',
            field=models.IntegerField(choices=[(120, '120'), (250, '250')]),
        ),
        migrations.AlterField(
            model_name='ssd',
            name='type',
            field=models.CharField(choices=[('SSD PLUS', 'SSD PLUS'), ('ULTRA', 'ULTRA')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('principal', 'distributor')},
        ),
        migrations.CreateModel(
            name='RequestSsd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(default=inventory.models.increment_doc_number, max_length=200)),
                ('implementation_date', models.DateField(verbose_name='date implementation')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='date updated')),
                ('document_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='date sent document')),
                ('document_received_back_at', models.DateTimeField(blank=True, null=True, verbose_name='date received back document')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='date approved')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.customer')),
                ('ssd', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.ssd')),
            ],
        ),
    ]
